export const userLogs = [
    {
      id: 2352,
      targetUser: 'Smith Harcules',
      action: 'Role Updated',
      changedBy: 'Admin User',
      changedByRole: 'superAdmin',
      timestamp: '2025-01-12T10:45:00Z',
      details: 'Role changed from "User" → "Manager"',
    },
    {
      id: 2351,
      targetUser: 'John Doe',
      action: 'Account Archived',
      changedBy: 'Super Admin',
      changedByRole: 'superAdmin',
      timestamp: '2025-01-11T14:22:00Z',
      details: 'User deactivated due to exit from company',
    },
    {
      id: 2350,
      targetUser: 'Jane Smith',
      action: 'Account Activated',
      changedBy: 'IT Admin',
      changedByRole: 'itAdmin',
      timestamp: '2025-01-10T09:30:00Z',
      details: 'Initial role set to "User"',
    },
    {
      id: 2349,
      targetUser: 'Mike Johnson',
      action: 'Password Changed',
      changedBy: 'Mike Johnson',
      changedByRole: 'vanRep',
      timestamp: '2025-01-09T16:15:00Z',
      details: 'Password updated successfully',
    },
    {
      id: 2348,
      targetUser: 'Sarah Wilson',
      action: 'Profile Updated',
      changedBy: 'Sarah Wilson',
      changedByRole: 'manager',
      timestamp: '2025-01-08T11:20:00Z',
      details: 'Email address updated from old@email.com to new@email.com',
    },
    {
      id: 2347,
      targetUser: 'David Brown',
      action: 'Role Updated',
      changedBy: 'Finance Manager',
      changedByRole: 'financeManager',
      timestamp: '2025-01-07T15:30:00Z',
      details: 'Role changed from "User" → "Finance Manager"',
    },
    {
      id: 2346,
      targetUser: 'Lisa Davis',
      action: 'Account Activated',
      changedBy: 'Supervisor',
      changedByRole: 'supervisor',
      timestamp: '2025-01-06T12:15:00Z',
      details: 'New user account created',
    },
  ];